//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrispySpoon.API.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbm_vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbm_vendor()
        {
            this.tbm_cafeteria = new HashSet<tbm_cafeteria>();
            this.tbm_fooditem = new HashSet<tbm_fooditem>();
        }
    
        public string vendor_code { get; set; }
        public string vendor_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbm_cafeteria> tbm_cafeteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbm_fooditem> tbm_fooditem { get; set; }
    }
}
