//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrispySpoon.API.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbm_cafeteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbm_cafeteria()
        {
            this.tbt_menu = new HashSet<tbt_menu>();
            this.tbm_facility = new HashSet<tbm_facility>();
        }
    
        public string cafeteria_code { get; set; }
        public string cafeteria_name { get; set; }
        public string vendor_code { get; set; }
    
        public virtual tbm_vendor tbm_vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbt_menu> tbt_menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbm_facility> tbm_facility { get; set; }
    }
}
