//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrispySpoon.API.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbt_order
    {
        public decimal order_id { get; set; }
        public decimal menu_id { get; set; }
        public decimal user_id { get; set; }
        public System.DateTime order_placed { get; set; }
        public Nullable<System.DateTime> order_delivered { get; set; }
        public Nullable<System.DateTime> order_printed { get; set; }
        public string order_status { get; set; }
        public byte[] order_qr_code { get; set; }
        public Nullable<decimal> order_rating { get; set; }
    
        public virtual tbt_menu tbt_menu { get; set; }
    }
}
