//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrispySpoon.API.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbt_menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbt_menu()
        {
            this.tbt_order = new HashSet<tbt_order>();
            this.tbm_fooditem = new HashSet<tbm_fooditem>();
        }
    
        public decimal menu_id { get; set; }
        public System.DateTime menu_date { get; set; }
        public string meal_type { get; set; }
        public string menu_item_name { get; set; }
        public string cafeteria_code { get; set; }
    
        public virtual tbm_cafeteria tbm_cafeteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbt_order> tbt_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbm_fooditem> tbm_fooditem { get; set; }
    }
}
