//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrispySpoon.API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crispyspoonDBEntities : DbContext
    {
        public crispyspoonDBEntities()
            : base("name=crispyspoonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbm_cafeteria> tbm_cafeteria { get; set; }
        public virtual DbSet<tbm_city> tbm_city { get; set; }
        public virtual DbSet<tbm_entitlement> tbm_entitlement { get; set; }
        public virtual DbSet<tbm_facility> tbm_facility { get; set; }
        public virtual DbSet<tbm_fooditem> tbm_fooditem { get; set; }
        public virtual DbSet<tbm_role> tbm_role { get; set; }
        public virtual DbSet<tbm_user> tbm_user { get; set; }
        public virtual DbSet<tbm_vendor> tbm_vendor { get; set; }
        public virtual DbSet<tbt_menu> tbt_menu { get; set; }
        public virtual DbSet<tbt_order> tbt_order { get; set; }
        public virtual DbSet<tbt_user_wishlist> tbt_user_wishlist { get; set; }
    }
}
