//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrispySpoon.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbm_cafeteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cafeteria()
        {
            FacilityCafeteriaMapping = new HashSet<FacilityCafeteriaMapping>();
            Menu = new HashSet<Menu>();
        }

        public string CafeteriaCode { get; set; }
        public string CafeteriaName { get; set; }
        public string VendorCode { get; set; }

        public Vendor Vendor { get; set; }
        public ICollection<FacilityCafeteriaMapping> FacilityCafeteriaMapping { get; set; }
        public ICollection<Menu> Menu { get; set; }
    }
}
